language: csharp
sudo: false

git:
  depth: 250

mono:
  - 4.2.1 # Default in Ubuntu Xenial, supported until April 2021

install:
  - nuget restore

script:
  - xbuild /p:Configuration=Release /p:Platform=mono "Radio Downloader.sln"
