before_build:
  - appveyor-retry nuget restore

version: "{build}"
clone_depth: 250

build:
  parallel: true
  project: Radio Downloader.sln

platform:
  - win32
  - win64

configuration: Package

artifacts:
  - path: installer/Radio_Downloader-win*.msi
